controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

profile_controllers:
    resource:
        path: ../src/Controller/Profile/
        namespace: App\Controller\Profile
    type: attribute
    prefix: /api/profile



# Explicitly register profile stats route
profile_stats:
    path: /api/profile/stats
    controller: App\Controller\Profile\ProfileDataController::getProfileStats
    methods: ['GET']

# Explicitly register profile completion acknowledgment route
profile_acknowledge_completion:
    path: /api/profile/acknowledge-completion
    controller: App\Controller\Profile\ProfileDataController::acknowledgeProfileCompletion
    methods: ['POST']

api_login_check:
    path: /api/login_check
    methods: ['POST']

api_token_refresh:
    path: /api/token/refresh
    methods: ['POST']
    controller: App\Controller\RefreshTokenController::refresh

api_token_revoke:
    path: /api/token/revoke
    methods: ['POST']
    controller: App\Controller\RefreshTokenController::revoke

api_token_revoke_all:
    path: /api/token/revoke-all
    methods: ['POST']
    controller: App\Controller\RefreshTokenController::revokeAll

api_token_devices:
    path: /api/token/devices
    methods: ['GET']
    controller: App\Controller\RefreshTokenController::listDevices

document_routes:
    resource: './routes/document.yaml'
