services:
  frontend:
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    volumes:
      # Retirer tous les volumes montés sur /var/www/symfony
      - backend_vendor:/var/www/symfony/vendor
      - backend_var:/var/www/symfony/var
      - jwt_keys:/var/www/symfony/config/jwt
    alpha: "./backend"
    beta: "docker://www-data@infra-backend-1:/var/www/symfony"

  nginx:
    volumes:
      # Utiliser un bind mount pour nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Mutagen s'occupera de synchroniser directement

volumes:
  # Supprimer cette définition
  # backend_nginx: