services:
  frontend:
    volumes:
      # Remove the host-to-container mount that Mutagen will handle
      # - ../frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    volumes:
      # Remove the host-to-container mount that Mutagen will handle
      # - ../backend:/var/www/symfony
      - backend_vendor:/var/www/symfony/vendor
      - backend_var:/var/www/symfony/var
      - jwt_keys:/var/www/symfony/config/jwt
      # Add the shared volume for nginx
      - backend_nginx:/var/www/symfony

  nginx:
    volumes:
      # Update nginx volume to use the backend container's filesystem
      # - ../backend:/var/www/symfony
      - backend_nginx:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  backend_nginx:
    # This is a named volume that will be used to share files between backend and nginx