services:
  frontend:
    volumes:
      # Remove the host-to-container mount that Mutagen will handle
      # - ../frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    volumes:
      # Remove the host-to-container mount that Mutagen will handle
      # - ../backend:/var/www/symfony
      - backend_vendor:/var/www/symfony/vendor
      - backend_var:/var/www/symfony/var
      - jwt_keys:/var/www/symfony/config/jwt
      # - backend_nginx:/var/www/symfony

  nginx:
    volumes:
      # On utilise un montage direct depuis le conteneur backend plutôt qu'un volume
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_started
    volumes_from:
      - backend:ro

volumes:
  backend_nginx:
    # Ce volume n'est plus utilisé, mais on le garde pour compatibilité