# This file defines the message cleanup schedule configuration
# In production, you should set up a cron job to run the cleanup command daily

services:
    # Message cleanup service configuration
    App\Service\MessageCleanupService:
        arguments:
            $messageRepository: '@App\Repository\MessageRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@logger'
        public: true

    # Message cleanup command configuration
    App\Command\CleanupOldMessagesCommand:
        arguments:
            $messageCleanupService: '@App\Service\MessageCleanupService'
        tags:
            - { name: 'console.command' }
