lexik_jwt_authentication:
    # Using absolute paths and hardcoded passphrase for testing
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 28800  # Durée de vie du token en secondes (8 heures)
    api_platform:
        check_path: /api/login_check
        username_path: email    # Ajout car vous utilisez email comme identifiant
        password_path: password

    # Explicitly define the default token extractor
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
