framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []
        # Activer les attributs de validation (ancien enable_annotations)
        enable_attributes: true
        # Configuration des contraintes globales
        mapping:
            paths:
                - "%kernel.project_dir%/src/Entity"
                # Le dossier Dto n'existe pas
                # - "%kernel.project_dir%/src/Dto" 
                # Le dossier Form n'existe peut-être pas non plus, vérifiez sa présence
                # - "%kernel.project_dir%/src/Form"
        
        # Contraintes de validation par défaut
        auto_mapping: true

when@test:
    framework:
        validation:
            not_compromised_password: false

# Contraintes personnalisées
doctrine:
    orm:
        entity_managers:
            default:
                # La section validation n'est plus supportée ici
                # validation:
                #     enabled: true
                
# Contraintes de validation spécifiques au mot de passe
# Ces contraintes s'appliquent à tous les formulaires et contrôleurs
parameters:
    app.password_constraints:
        min_length: 8
        max_length: 50
