version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - backend_vendor:/var/www/symfony/vendor
      - backend_var:/var/www/symfony/var
      - jwt_keys:/var/www/symfony/config/jwt
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    environment:
      REDIS_URL: redis://redis:6379
    command: bash -c "
      composer install --no-interaction && 
      echo 'Waiting for database...' &&
      php -r \"set_time_limit(30);for(;;){if(@fsockopen('database',3306))die('Database ready!\\n');echo '.';sleep(1);}\" &&
      php bin/console doctrine:database:create --if-not-exists --no-interaction &&
      php bin/console doctrine:schema:update --force --no-interaction &&
      php bin/console doctrine:fixtures:load --no-interaction --append || php bin/console doctrine:fixtures:load --no-interaction &&
      exec php-fpm"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ../backend:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-use-native-aio=0
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=0
      --max-allowed-packet=128M
      --skip-host-cache
      --skip-name-resolve
      --bind-address=0.0.0.0
      --log-error=/var/log/mysql/error.log
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bigproject
      MYSQL_USER: user
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - database_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-logs:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - "3306:3306"
    networks:
      - app-network
    # Utiliser un init system pour améliorer la gestion des signaux sur Windows
    init: true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    depends_on:
      - database
    networks:
      - app-network

  # Conteneur spécifique pour Windows 10 qui exécute le script de correction automatiquement
  mysql-win10-fix:
    image: mysql:8.0
    volumes:
      - ./mysql-init:/scripts
    command: bash -c "sleep 15 && mysql -h database -u root -proot < /scripts/init.sql || echo 'Retry...' && sleep 5 && mysql -h database -u root -proot < /scripts/init.sql"
    networks:
      - app-network
    depends_on:
      - database
    restart: "no"

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
  backend_vendor:
  backend_var:
  jwt_keys:
  redis_data: 