sync:
  backend:
    alpha: "../backend"
    beta: "docker://infra-backend-1/var/www/symfony"
    mode: "two-way-resolved"
    ignore:
      - "/vendor"
      - "/var"
      - "/config/jwt"
      - "/.git"
      - "/.idea"
      - "/.vscode"
      - "/.env.local"
      - "**/*.log"
    permissions:
      defaultFileMode: 0644
      defaultDirectoryMode: 0755
    symlink:
      mode: "portable"
    watch:
      pollingInterval: 1
    rescan:
      interval: 5
  
  # Nouvelle synchronisation du backend vers le volume partagé
  backend_volume:
    alpha: "docker://infra-backend-1/var/www/symfony"
    beta: "volume://backend_code"
    mode: "one-way-replica"
    ignore:
      - "/vendor"
      - "/var"
      - "/config/jwt"
      - "**/*.log"
    permissions:
      defaultFileMode: 0644
      defaultDirectoryMode: 0755
    symlink:
      mode: "portable"
    watch:
      pollingInterval: 1
    rescan:
      interval: 5
  
  frontend:
    alpha: "../frontend"
    beta: "docker://infra-frontend-1/app"
    mode: "two-way-resolved"
    ignore:
      - "/node_modules"
      - "/.git"
      - "/.idea"
      - "/.vscode"
      - "**/*.log"
      - "/dist"
    permissions:
      defaultFileMode: 0644
      defaultDirectoryMode: 0755
    symlink:
      mode: "portable"
    watch:
      pollingInterval: 1
    rescan:
      interval: 5 