sync:
  backend:
    alpha: "../backend"
    beta: "docker://infra-backend-1/var/www/symfony"
    mode: "two-way-resolved"
    ignore:
      - "/vendor"
      - "/var"
      - "/config/jwt"
      - "/.git"
      - "/.idea"
      - "/.vscode"
      - "/.env.local"
      - "**/*.log"
    permissions:
      defaultFileMode: 0644
      defaultDirectoryMode: 0755
    symlink:
      mode: "portable"
    watch:
      pollingInterval: 2
    rescan:
      # Rescan every 10 seconds if file watching fails
      interval: 10
  
  frontend:
    alpha: "../frontend"
    beta: "docker://infra-frontend-1/app"
    mode: "two-way-resolved"
    ignore:
      - "/node_modules"
      - "/.git"
      - "/.idea"
      - "/.vscode"
      - "**/*.log"
      - "/dist"
    permissions:
      defaultFileMode: 0644
      defaultDirectoryMode: 0755
    symlink:
      mode: "portable"
    watch:
      pollingInterval: 2
    rescan:
      interval: 10 