parameters:
    # Configuration des paramètres PHP pour l'encodage
    php_mbstring_encoding: 'UTF-8'

services:
    # Configurer l'encodage interne de PHP
    App\Service\PhpConfigInitializer:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_subscriber } 