when@dev:
    # Provide empty array properly - need to use {} for an empty routes definition
    # This completely disables the profiler routes
    
    # Original routes if you want to re-enable them later:
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler
